---
- name: Install python3-pip 4 Linux
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - python3-pip
    state: present

# https://groups.google.com/forum/#!topic/ansible-project/yO8dmKvNUIY
# https://github.com/ansible-ThoTeam/nexus3-oss/issues/205
- name: Install jmespath 4 Linux
  when:
    - ansible_system == 'Linux'
  # become: yes
  pip:
    name:
      - jmespath
    state: present

- name: Install GPG agent 4 deb-based distro
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - ansible_architecture == 'x86_64'
  become: yes
  apt:
    name: gnupg-agent
    state: present

- name: Create directory structure 4 test in docker
  when:
    - ansible_system == 'Linux'
    - ansible_virtualization_type == 'docker'
  become: yes
  file:
    path: /usr/share/man/man1
    state: directory
